local hl = vim.api.nvim_set_hl

local fg = 252
local bg = 'NONE'
local none = 'NONE'

hl(0, 'Normal', { ctermfg = fg, ctermbg = bg, bold = true })
hl(0, 'FoldColumn', { ctermfg = 102, ctermbg = bg, cterm = {} })
hl(0, 'SignColumn', { ctermfg = fg, ctermbg = bg, cterm = {} })
hl(0, 'VertSplit', { ctermfg = 59, ctermbg = none, cterm = {} })
hl(0, 'WinSeparator', { link = 'VertSplit' })
hl(0, 'ColorColumn', { ctermfg = none, ctermbg = 237, cterm = {} })
hl(0, 'Conceal', { ctermfg = 109, ctermbg = none, cterm = {} })
hl(0, 'Cursor', { ctermfg = none, ctermbg = none, cterm = { reverse = true } })
hl(0, 'lCursor', { link = 'Cursor' })
hl(0, 'iCursor', { link = 'Cursor' })
hl(0, 'vCursor', { link = 'Cursor' })
hl(0, 'TermCursor', { link = 'Cursor' })
hl(0, 'CursorLine', { ctermfg = none, ctermbg = 237, cterm = {} })
hl(0, 'CursorColumn', { link = 'CursorLine' })
hl(0, 'CursorLineNr', { ctermfg = 214, ctermbg = none, cterm = {} })
hl(0, 'TermCursorNC', { ctermfg = 237, ctermbg = 252, cterm = {} })

hl(0, 'DiffAdd', { ctermfg = 142, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'DiffChange', { ctermfg = 107, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'DiffDelete', { ctermfg = 203, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'DiffText', { ctermfg = 214, ctermbg = 235, cterm = { reverse = true } })

hl(0, 'GitSignsAdd', { ctermfg = 142, ctermbg = none, cterm = {} })
hl(0, 'GitSignsAddInline', { ctermfg = 235, ctermbg = 142, cterm = {} })
hl(0, 'GitSignsAddNr', { link = 'GitSignsAdd' })
hl(0, 'GitSignsAddLn', { link = 'GitSignsAdd' })
hl(0, 'GitSignsChange', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'GitSignsChangeInline', { ctermfg = 235, ctermbg = 107, cterm = {} })
hl(0, 'GitSignsChangeNr', { link = 'GitSignsChange' })
hl(0, 'GitSignsChangeLn', { link = 'GitSignsChange' })
hl(0, 'GitSignsDelete', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'GitSignsDeleteInline', { ctermfg = 235, ctermbg = 203, cterm = {} })
hl(0, 'GitSignsDeleteNr', { link = 'GitSignsDelete' })
hl(0, 'GitSignsDeleteLn', { link = 'GitSignsDelete' })

hl(0, 'Directory', { ctermfg = 142, ctermbg = none, cterm = { bold = true } })
hl(0, 'EndOfBuffer', { ctermfg = 235, ctermbg = none })
hl(0, 'Error', { ctermfg = 203, ctermbg = 235, cterm = { bold = true, reverse = true } })
hl(0, 'ErrorMsg', { ctermfg = 235, ctermbg = 203, cterm = { bold = true } })
hl(0, 'Folded', { ctermfg = 102, ctermbg = 237, cterm = {} })
hl(0, 'IncSearch', { ctermfg = 208, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'HighlightedyankRegion', { link = 'IncSearch' })
hl(0, 'LineNr', { ctermfg = 243, ctermbg = none, cterm = {} })
hl(0, 'MatchParen', { ctermfg = none, ctermbg = 59, cterm = { bold = true } })
hl(0, 'ModeMsg', { ctermfg = 214, ctermbg = none, cterm = { bold = true } })
hl(0, 'MoreMsg', { ctermfg = 214, ctermbg = none, cterm = { bold = true } })
hl(0, 'NonText', { ctermfg = 239, ctermbg = none, cterm = {} })

hl(0, 'Pmenu', { ctermfg = 252, ctermbg = none, cterm = {} })
hl(0, 'PmenuSbar', { ctermfg = none, ctermbg = 239, cterm = {} })
hl(0, 'PmenuSel', { ctermfg = 239, ctermbg = 109, cterm = { bold = true } })
hl(0, 'PmenuThumb', { ctermfg = none, ctermbg = 243, cterm = {} })

hl(0, 'Question', { ctermfg = 208, ctermbg = none, cterm = { bold = true } })
hl(0, 'Search', { ctermfg = 214, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'QuickFixLine', { link = 'Search' })
hl(0, 'SpecialKey', { ctermfg = 239, ctermbg = none, cterm = {} })

hl(0, 'SpellBad', { ctermfg = 203, ctermbg = none, cterm = { underline = true } })
hl(0, 'SpellCap', { ctermfg = 109, ctermbg = none, cterm = { underline = true } })
hl(0, 'SpellLocal', { ctermfg = 107, ctermbg = none, cterm = { underline = true } })
hl(0, 'SpellRare', { ctermfg = 175, ctermbg = none, cterm = { underline = true } })

hl(0, 'StatusLine', { ctermfg = 235, ctermbg = 252, cterm = { reverse = true } })
hl(0, 'StatusLineTerm', { link = 'StatusLine' })
hl(0, 'StatusLineNC', { ctermfg = 235, ctermbg = 137, cterm = { reverse = true } })
hl(0, 'StatusLineTermNC', { link = 'StatusLineNC' })
hl(0, 'TabLine', { ctermfg = 243, ctermbg = none, cterm = {} })
hl(0, 'TabLineFill', { ctermfg = 243, ctermbg = none, cterm = {} })
hl(0, 'TabLineSel', { ctermfg = none, ctermbg = 235, cterm = {} })
hl(0, 'Title', { ctermfg = 142, ctermbg = none, cterm = { bold = true } })
hl(0, 'Visual', { ctermfg = none, ctermbg = 59, cterm = {} })
hl(0, 'VisualNOS', { link = 'Visual' })
hl(0, 'WarningMsg', { ctermfg = 203, ctermbg = none, cterm = { bold = true } })
hl(0, 'WildMenu', { ctermfg = 109, ctermbg = 239, cterm = { bold = true } })

hl(0, 'Boolean', { ctermfg = 175, ctermbg = none, cterm = {} })
hl(0, 'Character', { ctermfg = 175, ctermbg = none, cterm = {} })
hl(0, 'Comment', { ctermfg = 102, ctermbg = none, cterm = { italic = true } })
hl(0, 'Conditional', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'Constant', { ctermfg = 175, ctermbg = none, cterm = {} })
hl(0, 'Define', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'Debug', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'Delimiter', { ctermfg = 208, ctermbg = none, cterm = {} })
hl(0, 'Error', { ctermfg = 203, ctermbg = 235, cterm = { bold = true, reverse = true } })
hl(0, 'Exception', { ctermfg = 203, ctermbg = none, cterm = { bold = true } })
hl(0, 'Float', { ctermfg = 175, ctermbg = none, cterm = {} })
hl(0, 'Function', { ctermfg = 142, ctermbg = none, cterm = { bold = true } })
hl(0, 'Structure', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'Include', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'PreProc', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'Number', { ctermfg = 175, ctermbg = none, cterm = {} })
hl(0, 'Operator', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'Keyword', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'String', { ctermfg = 142, ctermbg = none, cterm = {} })

hl(0, 'Identifier', { ctermfg = 109, ctermbg = none, cterm = {} })
hl(0, 'Ignore', { ctermfg = fg, ctermbg = none, cterm = {} })
hl(0, 'Label', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'Macro', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'PreCondit', { ctermfg = 107, ctermbg = none, cterm = {} })
hl(0, 'Repeat', { ctermfg = 203, ctermbg = none, cterm = {} })

hl(0, 'SpecialChar', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'SpecialComment', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'Statement', { ctermfg = 203, ctermbg = none, cterm = {} })
hl(0, 'StorageClass', { ctermfg = 208, ctermbg = none, cterm = {} })
hl(0, 'Special', { ctermfg = 208, ctermbg = none, cterm = {} })
hl(0, 'Tag', { link = 'Special' })
hl(0, 'Todo', { ctermfg = fg, ctermbg = 235, cterm = { bold = true } })
hl(0, 'Type', { ctermfg = 214, ctermbg = none, cterm = {} })
hl(0, 'Typedef', { ctermfg = 214, ctermbg = none, cterm = {} })
hl(0, 'Underlined', { ctermfg = 109, ctermbg = none, cterm = { underline = true } })
hl(0, 'CursorIM', { ctermfg = none, ctermbg = none, cterm = { reverse = true } })
hl(0, 'ToolbarLine', { ctermfg = none, ctermbg = 59, cterm = {} })
hl(0, 'ToolbarButton', { ctermfg = 230, ctermbg = 59, cterm = { bold = true } })
hl(0, 'Warnings', { ctermfg = 208, ctermbg = 235, cterm = { reverse = true } })

hl(0, 'NormalMode', { ctermfg = 137, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'InsertMode', { ctermfg = 109, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'ReplaceMode', { ctermfg = 107, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'VisualMode', { ctermfg = 208, ctermbg = 235, cterm = { reverse = true } })
hl(0, 'CommandMode', { ctermfg = 175, ctermbg = 235, cterm = { reverse = true } })

hl(0, 'NormalFloat', { ctermfg = 252, ctermbg = none, cterm = {} })
hl(0, 'FloatBorder', { ctermfg = 8, ctermbg = none, cterm = {} })

hl(0, 'LspReferenceText', { ctermfg = none, ctermbg = 240, cterm = {} })
hl(0, 'LspReferenceRead', { ctermfg = none, ctermbg = 240, cterm = {} })
hl(0, 'LspReferenceWrite', { ctermfg = none, ctermbg = 240, cterm = {} })

hl(0, 'Treesitter', { link = 'StatusLineNC' })
